name: "Setup env"
description: "Sets up node and installs yarn dependencies"
inputs:
  NAME:
    description: "Image name"
    required: true
  FILE:
    description: "Path to Dockerfile"
    required: true
  CONTEXT:
    description: "Path to build context"
    required: true
  PLATFORMS:
    description: "Supported platforms"
    required: false
    default: "linux/amd64,linux/arm64"
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: echo "version=$(cat ./VERSION)" >> $GITHUB_ENV

    - name: clone aath
      run: |
        cd env
        make clone

    - uses: docker/build-push-action@v3
      with:
        platforms: ${{inputs.PLATFORMS}}
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/findy-agent-backchannel/${{inputs.NAME}}:${{ env.version }}
          ghcr.io/${{ github.repository_owner }}/findy-agent-backchannel/${{inputs.NAME}}:latest
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/findy-agent-backchannel/${{inputs.NAME}}:latest
        cache-to: type=inline
        context: ${{inputs.CONTEXT}}
        file: ${{inputs.FILE}}
