name: bundle
on:
  push:
    tags:
      - "*"
  repository_dispatch:
  workflow_dispatch:

jobs:
  test-bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build findy
        run: docker build -t findy-agent-backchannel -f ./aath/Dockerfile .
      - uses: actions/checkout@v2
        with:
          repository: "hyperledger/aries-agent-test-harness"
          ref: "main"

      - name: build acapy
        run: ./manage build -a acapy-main

      - name: start ledger
        run: |
          ./manage service start von-network
          cd services/von-network/.build/von-network
          ./manage build

      - name: run test
        run: |
          ./manage run -d acapy-main -b findy -t @AcceptanceTest -t @AIP10 -t ~@wip -t ~@revocation > output.log
          cat output.log
          cat output.log | grep "3 features passed"
        env:
          NO_TTY: "1"

  push-bundle:
    needs: test-bundle
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: set version
        run: |
          NEW_AGENT_VERSION=$(curl https://raw.githubusercontent.com/findy-network/findy-agent/master/VERSION)
          echo $NEW_AGENT_VERSION > ./AGENT_VERSION

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "version=$(cat ./VERSION)" >> $GITHUB_ENV
      - run: echo "agentVersion=$(cat ./AGENT_VERSION)" >> $GITHUB_ENV

      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/findy-agent-backchannel:findy-bc-bundle-${{ env.version }}.agent-${{ env.agentVersion }}
            ghcr.io/${{ github.repository_owner }}/findy-agent-backchannel:findy-bc-bundle-latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/findy-agent-backchannel:findy-bc-bundle-latest
          cache-to: type=inline
          context: .
          file: ./aath/Dockerfile
