name: release
on:
 push:
   tags:
     - '*'

jobs:

  full-iop:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test findy as Bob
        run: |
          cd ./env
          make aath-check \
            AGENT_DEFAULT=acapy \
            AGENT_BOB=findy
        env:
          NO_TTY: "1"
      - name: test findy as Acme
        run: |
          cd ./env
          make aath-check \
            AGENT_DEFAULT=findy \
            AGENT_BOB=acapy
        env:
          NO_TTY: "1"

  push-images:
    needs: full-iop
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "version=$(cat ./VERSION)" >> $GITHUB_ENV

      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/findy-agent-backchannel:findy-bc-${{ env.version }}
            ghcr.io/${{ github.repository_owner }}/findy-agent-backchannel:findy-bc-latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/findy-agent-backchannel:findy-bc-latest
          cache-to: type=inline

      - name: clone acapy-bc
        run: |
          cd env
          make clone

      - uses: docker/build-push-action@v2
        with:
          # no acapy support yet for linux/arm64
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/findy-agent-backchannel:acapy-bc-${{ env.version }}
            ghcr.io/${{ github.repository_owner }}/findy-agent-backchannel:acapy-bc-latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/findy-agent-backchannel:acapy-bc-latest
          cache-to: type=inline
          context: ./env/.docker/aries-agent-test-harness/aries-backchannels
          file: ./env/.docker/aries-agent-test-harness/aries-backchannels/acapy/Dockerfile.acapy

      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/findy-agent-backchannel:aath-${{ env.version }}
            ghcr.io/${{ github.repository_owner }}/findy-agent-backchannel:aath-latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/findy-agent-backchannel:aath-latest
          cache-to: type=inline
          context: ./env/.docker/aries-agent-test-harness/aries-test-harness
          file: ./env/.docker/aries-agent-test-harness/aries-test-harness/Dockerfile.harness

  merge:
    needs: push-images
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: merge
        run:  |
          git fetch --tags origin
          git merge $GITHUB_REF
          git push origin master