name: test
on: push
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: go test ./...
      - name: scan
        run: make scan
  iop:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test findy as Bob
        run: |
          cd ./env
          make aath-check \
            AGENT_DEFAULT=acapy \
            AGENT_BOB=findy \
            INCLUDE_TAGS='@T001-RFC0160,@T001-RFC0036,@T001-RFC0037'
        env:
          NO_TTY: "1"
      - name: test findy as Acme
        run: |
          cd ./env
          make aath-test-check \
            AGENT_DEFAULT=findy \
            AGENT_BOB=acapy \
            INCLUDE_TAGS=@T001-RFC0160
        env:
          NO_TTY: "1"

